# Generated by Django 4.1.7 on 2023-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_percent",
            field=models.IntegerField(default=0),
        ),
    ]
